### ISSUE TITLE
Does it work with iOS projects?

### ISSUE THREAD

**Issue by niil-ohlin** [loiclec/FuzzCheck#1]
I'm very curious to try this out specifically for ios projects.

**Comment by loiclec** [comment]
Hi Niil. I suppose there is a way to make it work with iOS projects, but I haven't tried it myself. The two important steps to use FuzzCheck are:
- use a development version of the Swift compiler
- when compiling the targets you want to test, add the option `-sanitize=fuzzer`. It will instrument them with LLVM's SanitizerCoverage, which FuzzCheck needs to determine the relative worth of a test input. Do not use the option `-sanitize=fuzzer` at link time.
 
Let me know if you still want to try it and if you need more precise instructions

**Comment by dhhyuk** [comment]
Hi loiclec.
i had follow `Using FuzzCheck` in README.

Result
```
https://github.com/apple/swift-llbuild.git @ master: error: manifest parse error(s):
/var/folders/jg/xdpwlrz969z055b2l7bprpvh0000gn/T/TemporaryFile.jTMFFQ.swift:8:22: error: incorrect argument label in call (have 'name:platforms:products:targets:cxxLanguageStandard:', expected 'name:pkgConfig:products:targets:cxxLanguageStandard:')
let package = Package(
```

i think, didn't set compiler option `-sanitize=fuzzer`. 
How can resolve this problem and add this option??

**Comment by loiclec** [comment]
Hi @dhhyuk ,

I stopped developing FuzzCheck for Swift 2 years ago. Since then, I have [rewritten it in Rust](https://github.com/loiclec/fuzzcheck-rs). I am not sure what causes the error message you're seeing. But I would guess that changes in the Swift language made some of the code for my fork of SwiftPM not valid anymore. There is little to do about it apart from reviewing and updating FuzzCheck. But my focus is entirely on the Rust version for now, so I will not have the time to do that, sorry :(

I am going to update the readme and will archive the repository soon, so that it is more clear that FuzzCheck’s development has moved to Rust.
